language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -qq libeigen3-dev libboost-system-dev libboost-thread-dev libtinyxml-dev
  - sudo apt-get --force-yes install icub
  - sudo apt-get install cmake

before_script:
  - cmake --version
  - cd ..
  # Prepare paramHelp build
  - cd paramHelp
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - sudo make install
  - ctest -V

notifications:
  email:
    - pegua1@gmail.com
